#!/usr/bin/env bash
#Installs Nginx and configures it on a remote Server
#Nginx should be listening to port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
