#!/usr/bin/env bash
#Installs Nginx and configures it on a remote Server
#Nginx should be listening to port 80
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" |  /var/www/html/index.nginx-debian.html
sudo service nginx start
