#!/usr/bin/env bash
# Displays a list of currently running processes containing the bash keyword.
# shellcheck disable=SC2009
# allowing you to easily get the PID of your Bash process

ps -aux | grep bash
