#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
#    Display hours from 0 to 12
#    Display minutes from 1 to 39

hour=0

while [ $hour -le 12 ]
do 
  echo "Hour: $Hour"
  minutes=1
  while [ $minute -le 39 ]
  do
    echo "$minutes"
    (( minutes++ ))
  done
   (( hour++))
  done
