#!/usr/bin/env bash
# installs ufw firewall and allows only the following ports
# Port 22
# Port 433
# Port 80

sudo apt-get -y update
sudo apt-get -y unistall ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
