#!/usr/bin/env bash
# installs ufw firewall and allows only the following ports
# Port 22
# Port 433
# Port 80

apt-get -y update
apt-get -y unstall ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
